export default {
  margin: {
    alias: 'm',
  },
  marginTop: {
    alias: 'mt',
  },
  marginRight: {
    alias: 'mr',
  },
  marginBottom: {
    alias: 'mb',
  },
  marginLeft: {
    alias: 'ml',
  },
  padding: {
    alias: 'p',
  },
  paddingTop: {
    alias: 'pt',
  },
  paddingRight: {
    alias: 'pr',
  },
  paddingBottom: {
    alias: 'pb',
  },
  paddingLeft: {
    alias: 'pl',
  },
  fontSize: {},
  textColor: {},
  color: {},
  fontFamily: {},
  textAlign: {},
  lineHeight: {},
  fontWeight: {},
  fontStyle: {},
  letterSpacing: {},
  display: {},
  width: {},
  maxWidth: {},
  minWidth: {},
  height: {},
  maxHeight: {},
  minHeight: {},
  sizeWidth: {},
  sizeHeight: {},
  size: {},
  ratioPadding: {},
  ratio: {},
  verticalAlign: {},
  alignItems: {},
  alignContent: {},
  justifyItems: {},
  justifyContent: {},
  flexWrap: {},
  flexBasis: {},
  flexDirection: {},
  flex: {},
  justifySelf: {},
  alignSelf: {},
  order: {},
  gridGap: {},
  gridColumnGap: {},
  gridRowGap: {},
  gridColumn: {},
  gridRow: {},
  gridAutoFlow: {},
  gridAutoColumns: {},
  gridAutoRows: {},
  gridTemplateColumns: {},
  gridTemplateRows: {},
  gridTemplateAreas: {},
  gridArea: {},
  border: {},
  borderTop: {},
  borderRight: {},
  borderBottom: {},
  borderLeft: {},
  borders: {},
  borderColor: {},
  borderRadius: {},
  boxShadow: {},
  opacity: {},
  overflow: {},
  background: {},
  backgroundColor: {
    alias: 'bg',
  },
  backgroundImage: {},
  backgroundPosition: {},
  backgroundRepeat: {},
  backgroundSize: {},
  position: {},
  zIndex: {},
  top: {},
  right: {},
  bottom: {},
  left: {},
  textStyle: {},
  colorStyle: {},
  buttonStyle: {},
};
